/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as HostsSlugRouteImport } from './routes/hosts/$slug'
import { Route as EventsIdIndexRouteImport } from './routes/events/$id/index'
import { Route as EventsIdCheckinRouteImport } from './routes/events/$id/checkin'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard/events/new'
import { Route as DashboardEventsIdRouteImport } from './routes/dashboard/events/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsSlugRoute = HostsSlugRouteImport.update({
  id: '/hosts/$slug',
  path: '/hosts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdIndexRoute = EventsIdIndexRouteImport.update({
  id: '/events/$id/',
  path: '/events/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdCheckinRoute = EventsIdCheckinRouteImport.update({
  id: '/events/$id/checkin',
  path: '/events/$id/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/dashboard/events/new',
  path: '/dashboard/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsIdRoute = DashboardEventsIdRouteImport.update({
  id: '/dashboard/events/$id',
  path: '/dashboard/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/events/$id/': typeof EventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/events/$id': typeof EventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/events/$id/': typeof EventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/my-events'
    | '/my-tickets'
    | '/profile'
    | '/reset-password'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/dashboard/'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/events/$id/checkin'
    | '/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/my-events'
    | '/my-tickets'
    | '/profile'
    | '/reset-password'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/dashboard'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/events/$id/checkin'
    | '/events/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explore'
    | '/my-events'
    | '/my-tickets'
    | '/profile'
    | '/reset-password'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/dashboard/'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/events/$id/checkin'
    | '/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  MyEventsRoute: typeof MyEventsRoute
  MyTicketsRoute: typeof MyTicketsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  HostsSlugRoute: typeof HostsSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsIdRoute: typeof DashboardEventsIdRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  EventsIdCheckinRoute: typeof EventsIdCheckinRoute
  EventsIdIndexRoute: typeof EventsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$slug': {
      id: '/hosts/$slug'
      path: '/hosts/$slug'
      fullPath: '/hosts/$slug'
      preLoaderRoute: typeof HostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/': {
      id: '/events/$id/'
      path: '/events/$id'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof EventsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/checkin': {
      id: '/events/$id/checkin'
      path: '/events/$id/checkin'
      fullPath: '/events/$id/checkin'
      preLoaderRoute: typeof EventsIdCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/dashboard/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/$id': {
      id: '/dashboard/events/$id'
      path: '/dashboard/events/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof DashboardEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  MyEventsRoute: MyEventsRoute,
  MyTicketsRoute: MyTicketsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  HostsSlugRoute: HostsSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsIdRoute: DashboardEventsIdRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  EventsIdCheckinRoute: EventsIdCheckinRoute,
  EventsIdIndexRoute: EventsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
